kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# the control plane node
- role: control-plane
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "DynamicProvisioningScheduling=true"
  scheduler:
    extraArgs:
      "feature-gates": "DynamicProvisioningScheduling=true"
  controllerManager:
    extraArgs:
      "feature-gates": "DynamicProvisioningScheduling=true"
- |
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "DynamicProvisioningScheduling=true"
- |
  kind: KubeletConfiguration
  featureGates:
    DynamicProvisioningScheduling: true
- |
  kind: KubeProxyConfiguration
  featureGates:
    DynamicProvisioningScheduling: true
