name: CI

on:
  push:
    branches-ignore:
      - 'release-*'
    tags-ignore:
      - '*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster:
        - {"version": "v1.11.10", "config": "kind.yaml"}
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Create Kubernetes ${{ matrix.cluster.version }} cluster
      id: kind
      uses: engineerd/setup-kind@v0.1.0
      with:
        version: v0.6.1
        config: hack/kubernetes/${{ matrix.cluster.config }}
        image: kindest/node:${{ matrix.cluster.version }}

    - name: Prepare cluster for testing
      id: local-path
      run: |
        kubectl version

    - name: Prepare cluster for testing
      id: local-path
      run: |
        echo "waiting for nodes to be ready ..."
        kubectl wait --for=condition=Ready nodes --all --timeout=5m
        kubectl get nodes
        echo
        echo "installing local-path provisioner ..."
        kubectl delete storageclass --all
        kubectl apply -f https://github.com/rancher/local-path-provisioner/raw/v0.0.11/deploy/local-path-storage.yaml
        kubectl wait --for=condition=Ready pods -n local-path-storage --all --timeout=5m
        kubectl apply -f hack/kubernetes/storageclass/standard.yaml
